# -*- coding: utf-8 -*-

"""A module with utils for Cloud Formation workflows."""


def create_cf_template(username, password, email):
    """Create a Cloud Formation template."""
    template = []
    template.append('{')
    template.append('  "AWSTemplateFormatVersion": "2010-09-09",')
    template.append('  "Parameters": {')
    template.append('    "ContainerNameParameter": {')
    template.append('      "Type": "String",')
    template.append('      "Description": "Enter a name for the running container"')
    template.append('    },')
    template.append('    "ImageParameter": {')
    template.append('      "Type": "String",')
    template.append('      "Description": "Enter a registry image (and tag)"')
    template.append('    },')
    template.append('    "MinSizeParameter": {')
    template.append('      "Type": "Number",')
    template.append('      "Default": "1",')
    template.append('      "Description": "Enter the min size"')
    template.append('    },')
    template.append('    "MaxSizeParameter": {')
    template.append('      "Type": "Number",')
    template.append('      "Default": "1",')
    template.append('      "Description": "Enter the max size"')
    template.append('    }')
    template.append('  },')
    template.append('  "Resources": {')
    template.append('    "ReeferLaunchConfig": {')
    template.append('      "Type": "AWS::AutoScaling::LaunchConfiguration",')
    template.append('      "Properties": {')
    template.append('        "AssociatePublicIpAddress": "true",')
    template.append('        "ImageId": "ami-e3106686",')
    template.append('        "InstanceType": "t2.micro",')
    template.append('        "KeyName": "quickly_fitchet",')
    template.append('        "SecurityGroups": [')
    template.append('          "sg-be4db7d8"')
    template.append('        ],')
    template.append('        "UserData": {')
    template.append('          "Fn::Base64": {')
    template.append('            "Fn::Join": [')
    template.append('              "",')
    template.append('              [')
    template.append('                "#!/bin/bash -xe\\n",')
    template.append('                "\\n",')
    template.append('                "# Install and start docker.\\n",')
    template.append('                "yum install -y docker\\n",')
    template.append('                "service docker start\\n",')
    template.append('                "chkconfig docker on\\n",')
    template.append('                "\\n",')
    if username and password and email:
        template.append('                "# Authenticate with docker hub.\\n",')
        template.append('                "docker login \\\\n",')
        template.append('                "    -u ' + username + ' \\\\n",')
        template.append('                "    -p ' + password + ' \\\\n",')
        template.append('                "    -e ' + email + '\\n",')
        template.append('                "\\n",')
    template.append('                "# Pull the docker image.\\n",')
    template.append('                "docker pull ", {"Ref": "ImageParameter"}, " \\n",')
    template.append('                "\\n",')
    template.append('                "# Start the container.\\n",')
    template.append('                "docker run",')
    template.append('                "    --name ", {"Ref": "ContainerNameParameter"},')
    template.append('                "    --restart always",')
    template.append('                "    -dti",')
    template.append('                "    -p 80:80",')
    template.append('                "    ", {"Ref": "ImageParameter"}, "\\n",')
    template.append('                "\\n"')
    template.append('              ]')
    template.append('            ]')
    template.append('          }')
    template.append('        }')
    template.append('      }')
    template.append('    },')
    template.append('    "ReeferASG": {')
    template.append('      "Type": "AWS::AutoScaling::AutoScalingGroup",')
    template.append('      "Properties": {')
    template.append('        "LaunchConfigurationName": {"Ref": "ReeferLaunchConfig"},')
    template.append('        "MinSize": "1",')
    template.append('        "MaxSize": "1",')
    template.append('        "VPCZoneIdentifier": [')
    template.append('          "subnet-a1e1f9d6",')
    template.append('          "subnet-33d2e06a"')
    template.append('        ]')
    template.append('      }')
    template.append('    }')
    template.append('  }')
    template.append('}')
    return "\n".join(template)
